### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by nininishishishi** [nininishishishi/protospace-38733#1]
https://protospace-38733.onrender.com/prototypes

**Comment by shodai-ito** [comment]
@nininishishishi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **トップページの意図せぬ箇所にログインユーザー名が表示されています**
こちらの箇所にユーザー名の表示は不要ですので削除しましょう。
<img width="450" alt="スクリーンショット 2023-03-26 10 46 37" src="https://user-images.githubusercontent.com/62537107/227750854-572efd38-10bd-469f-89b6-272364f28820.png">

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
一部ユーザー名が正しく表示されておりません。
<img width="582" alt="スクリーンショット 2023-03-26 10 46 11" src="https://user-images.githubusercontent.com/62537107/227750877-0c691080-9271-4bde-87a0-f8851f23bc8d.png">

- [x] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされること**
ログインページでなく、トップページにリダイレクトされてしまいます。
【チェック方法】
最初にログアウト状態を作る。投稿ページ・編集ページのURLを打ち込み、ログインページにリダイレクトされれば正常な挙動。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shodai-ito** [comment]
@nininishishishi さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。

**Comment by nininishishishi** [comment]
@shodai-ito 
ありがとうございます！！
